### ISSUE TITLE
Assignment 3

### ISSUE THREAD

**Issue by blackboxlogic** [joshBremser/Cos470#3]
You're expecting the times and locations to be exact matches which will never happen.

Your `haveWeMet()` algorithm is O(n^2). That won't do.

**Comment by joshBremser** [comment]
Fixed in ab533a0

**Comment by blackboxlogic** [comment]
### Data model
yep
### Business logic
* Your haveWeMet() algorithm is O(n^2): -5 pts
* The fuzzy-ness of the match isn't configurable: -2 pts
### Tests
Unit test don't compile: -5 pts
### Api
Controller: looks good
Evidence of the API response: Yep
### Organization
Needs gitIgnore folders: -3 points
* bin 
* obj
* .vs
